CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TYPE spatial_type AS ENUM ('COUNTRY','PROVINCE','DISTRICT','DS_DIVISION','GN_DIVISION');
CREATE TYPE weather_node_density AS ENUM ('DENSE','STANDARD','SPARSE');
CREATE TYPE disaster_severity AS ENUM ('LOW','MODERATE','HIGH','CRITICAL','EXTREME');
CREATE TYPE disaster_category AS ENUM ('FLOOD','LANDSLIDE','CYCLONE','FIRE','TSUNAMI','DROUGHT','STORM','LIGHTNING','HEAT_WAVE','COASTAL_EROSION');
CREATE TYPE report_status AS ENUM ('PENDING','VERIFIED','REJECTED','ARCHIVED');
CREATE TYPE warning_status AS ENUM ('PROPOSED','ACTIVE','RESOLVED','REJECTED');
CREATE TYPE task_status AS ENUM ('OPEN','ASSIGNED','EN_ROUTE','ON_SITE','COMPLETED','CANCELLED');
CREATE TYPE sos_status AS ENUM ('PENDING','ASSIGNED','EN_ROUTE','RESOLVED');
CREATE TYPE alert_level AS ENUM ('NORMAL','ALERT','MINOR_FLOOD','MAJOR_FLOOD');
CREATE TYPE notification_channel AS ENUM ('EMAIL','PUSH','INAPP');
CREATE TYPE source_api AS ENUM ('OPEN_METEO','OPENWEATHERMAP','ARCGIS','RIVERNET');
